version: '3'
services:
  database:
    container_name: characters_container
    build:
      context: ../../
      dockerfile: tools/docker/development/Dockerfile.postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=characters_database
    ports:
      - "5432:5432"
  redis:
    container_name: characters_redis
    build: 
      context: ../../
      dockerfile: tools/docker/development/Dockerfile.redis
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=
    ports:
      - "6379:6379"